apiVersion: v1
kind: Pod
metadata:
  name: "mydb1"
  labels:
    app: "mydb"
spec:
  containers:
    - name: "mydb"
      image: "mysql:5.7"
      env:
        -name: MYSQL_ROOT_PASSWORD
         value: redhat

        -name: MYSQL_DATABASE
         value: mydb1

        -name: MYSQL_USER
         value: sid

        -name: MYSQL_PASS
         value: redhat