apiVersion: v1
kind: Service
metadata:
  name: mylb1
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8080
      nodePort: 32000